packages:
  - apps/*
  - packages/*

catalog:
  '@tabler/icons-react': ^3.36.1
  '@types/node': 25.0.10
  '@types/react': 19.2.10
  '@types/react-dom': 19.2.3
  motion: ^12.29.2
  sonner: ^2.0.7
  vitest: ^4.0.18
  zod: ^4.3.6

onlyBuiltDependencies:
  - '@posthog/cli'
  - '@swc/core'
  - bufferutil
  - core-js
  - esbuild
  - msw
  - protobufjs
  - puppeteer
  - sharp

overrides:
  '@types/react': 19.2.10
  '@types/react-dom': 19.2.3
  next: 16.1.6
  react: 19.2.4
  react-dom: 19.2.4

publicHoistPattern:
  - '@sparticuz/chromium'
  - puppeteer-core
