packages:
  - apps/*
  - packages/*

catalog:
  '@formatjs/intl-datetimeformat': ^7.4.5
  '@formatjs/intl-getcanonicallocales': ^3.2.8
  '@formatjs/intl-locale': ^5.3.7
  '@formatjs/intl-numberformat': ^9.3.8
  '@formatjs/intl-pluralrules': ^6.3.7
  '@formatjs/intl-relativetimeformat': ^12.3.7
  '@lingui/babel-plugin-lingui-macro': 6.0.1
  '@lingui/cli': 6.0.1
  '@lingui/conf': 6.0.1
  '@lingui/core': 6.0.1
  '@lingui/format-po': 6.0.1
  '@lingui/message-utils': 6.0.1
  '@lingui/react': 6.0.1
  '@lingui/swc-plugin': 6.0.0
  '@tabler/icons-react': ^3.44.0
  '@tanstack/react-query': ^5.100.10
  '@trpc/client': ^11.17.0
  '@trpc/server': ^11.17.0
  '@trpc/tanstack-react-query': ^11.17.0
  '@types/node': 25.8.0
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vercel/functions': ^3.6.0
  clsx: ^2.1.1
  cva: 1.0.0-beta.4
  date-fns: ^4.1.0
  ipaddr.js: ^2.4.0
  lru-cache: ^11.3.6
  motion: ^12.38.0
  msw: ^2.14.6
  posthog-js: ^1.373.5
  rdapper: ^0.13.0
  react: 19.2.6
  react-dom: 19.2.6
  sonner: ^2.0.7
  superjson: ^2.2.6
  tailwind-merge: ^3.6.0
  tailwindcss: ^4.3.0
  typescript: 6.0.3
  vitest: ^4.1.6
  zod: ^4.4.3
  zustand: ^5.0.13

ignoredBuiltDependencies:
  - '@google/genai'
  - '@nestjs/core'

onlyBuiltDependencies:
  - '@posthog/cli'
  - '@swc/core'
  - bufferutil
  - cbor-extract
  - core-js
  - esbuild
  - msgpackr-extract
  - msw
  - protobufjs
  - puppeteer
  - sharp

overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3

publicHoistPattern:
  - '@sparticuz/chromium'
  - puppeteer-core
