packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@posthog/cli'
  - '@swc/core'
  - bufferutil
  - core-js
  - esbuild
  - msw
  - protobufjs
  - puppeteer
  - sharp

overrides:
  '@types/react': 19.2.9
  '@types/react-dom': 19.2.3
  next: 16.1.5
  react: 19.2.4
  react-dom: 19.2.4

publicHoistPattern:
  - '@sparticuz/chromium'
  - puppeteer-core
