packages:
  - apps/*
  - packages/*
catalog:
  '@opentelemetry/api': ^1.9.1
  '@opentelemetry/api-logs': ^0.222.0
  '@opentelemetry/exporter-logs-otlp-http': ^0.222.0
  '@opentelemetry/instrumentation': ^0.222.0
  '@opentelemetry/resources': ^2.11.0
  '@opentelemetry/sdk-logs': ^0.222.0
  '@opentelemetry/sdk-metrics': ^2.11.0
  '@opentelemetry/sdk-trace-base': ^2.11.0
  '@tabler/icons-react': ^3.46.0
  '@trpc/client': ^11.19.0
  '@trpc/server': ^11.19.0
  '@trpc/tanstack-react-query': ^11.19.0
  '@types/node': ^24.13.5
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
  '@vercel/functions': ^3.9.8
  ipaddr.js: ^2.5.0
  motion: ^13.4.0
  msw: ^2.15.0
  rdapper: ^0.15.1
  sonner: ^2.0.8
  superjson: ^2.2.6
  vitest: ^5.0.1
  workflow: 5.0.0-beta.53
  zod: ^4.6.5
publicHoistPattern:
  - '@sparticuz/chromium'
  - puppeteer-core
allowBuilds:
  '@posthog/cli': true
  '@swc/core': true
  bufferutil: true
  cbor-extract: true
  core-js: true
  esbuild: true
  msw: true
  protobufjs: true
  puppeteer: true
  sharp: true
  '@nestjs/core': false
minimumReleaseAgeExclude:
  - rdapper@0.15.1
